Repository Team18-Mogazoa/MOGAZOA, pull requests merged in 2024-05, with the labels that each got.

#15 feat: #7: 컬러추가
  src/app/globals.css
  src/app/page.tsx
  tailwind.config.ts
Labels: feat

#18 5 feat button
  public/Icons/floating-icon.svg
  src/Components/Commons/Button/FloatingButton/index.tsx
  src/Components/Commons/Button/PrimaryButton/index.tsx
  src/Components/Commons/Button/SecondaryButton/index.tsx
  src/Components/Commons/Button/TertiaryButton/index.tsx
  src/Types/1
  src/Types/ButtonProps.ts
  src/app/layout.tsx
  tailwind.config.ts
Labels: ✨components

#23 21 feat chip
  src/Components/Commons/Chip/CategoryChip/index.tsx
  src/Components/Commons/Chip/RankingChip/index.tsx
  tailwind.config.ts
Labels: ✨components

#27 refactor : 공통 버튼 컴포넌트 리팩토링(코드리뷰반영)
  src/Components/Commons/Button/PrimaryButton/index.tsx
  src/Components/Commons/Button/SecondaryButton/index.tsx
  src/Components/Commons/Button/TertiaryButton/index.tsx
  src/Components/Commons/Button/index.tsx
  tailwind.config.ts
Labels: ✨components, ⚙refactor

#32 11 feat api setting
  package-lock.json
  package.json
  src/Apis/Auth/Auth.service.ts
  src/Apis/Auth/Auth.type.ts
  src/Apis/Auth/queries.ts
  src/Apis/Auth/useAuthService.ts
  src/Apis/Category/Category.service.ts
  src/Apis/Category/Category.type.ts
  src/Apis/Category/queries.ts
  src/Apis/Category/useCategoryService.ts
  src/Apis/Follow/Follow.service.ts
  src/Apis/Follow/Follow.type.ts
  src/Apis/Follow/queries.ts
  src/Apis/Follow/useFollowService.ts
  src/Apis/Oauth/.gitkeep
  src/Apis/Product/.gitkeep
  src/Apis/Review/.gitkeep
  src/Apis/Utils.ts
  src/Apis/common.type.ts
  src/Apis/interceptors.ts
  src/Apis/requestor.ts
  src/Constant/1
  src/app/Providers.tsx
  src/app/layout.tsx
Labels: feat

#35 11 feat api setting(2)
  src/Apis/Category/Category.type.ts
  src/Apis/Image/Image.service.ts
  src/Apis/Image/Image.type.ts
  src/Apis/Image/queries.ts
  src/Apis/Image/useImageService.ts
  src/Apis/Product/.gitkeep
  src/Apis/Product/Product.service.ts
  src/Apis/Product/Product.type.ts
  src/Apis/Product/queries.ts
  src/Apis/Product/useProduct.Service.ts
  src/Apis/Review/.gitkeep
  src/Apis/Review/Review.service.ts
  src/Apis/Review/Review.type.ts
  src/Apis/Review/queries.ts
  src/Apis/Review/useReview.Service.ts
  src/Apis/User/User.service.ts
  src/Apis/User/User.type.ts
  src/Apis/User/queries.ts
  src/Apis/User/useUserService.ts
  src/Apis/common.type.ts
Labels: feat, 🤔continue

#34 20 feat homepage (중간 완성)
  .eslintrc.json
  package-lock.json
  package.json
  src/Components/1
  src/Components/Commons/1
  src/Components/Commons/Profile/index.tsx
  src/Components/HomeComponents/Products/ProductsCategory/index.tsx
  src/Components/HomeComponents/Products/index.tsx
  src/Components/HomeComponents/Products/productMockData.json
  src/Components/HomeComponents/ReviewRank/RankProfile/index.tsx
  src/Components/HomeComponents/ReviewRank/index.tsx
  src/Components/HomeComponents/ReviewRank/mockData.json
  src/Components/HomeComponents/Sidemenu/index.tsx
  src/Constant/Categories.ts
  src/Constant/SortingOption.ts
  src/Hooks/1
  src/Types/ButtonProps.ts
  src/Types/ProductType.ts
  src/Types/UserProfile.ts
  src/app/layout.tsx
  src/app/page.tsx
Labels: 📃pages, 🤔continue
