Repository Team18-Mogazoa/MOGAZOA, pull requests merged in 2024-06, with the labels that each got.

#37 36 feat 모달 컨테이너 생성
  package-lock.json
  package.json
  src/Components/Commons/ModalContainer/ModalContainer.tsx
  src/Context/ModalContext.tsx
  src/app/layout.tsx
Labels: feat

#42 fix: User API 수정
  src/Apis/Product/Product.service.ts
  src/Apis/Product/Product.type.ts
  src/Apis/Product/queries.ts
  src/Apis/Product/useProduct.Service.ts
  src/Apis/User/User.service.ts
  src/Apis/User/queries.ts
  src/Apis/User/useUserService.ts
  src/app/Providers.tsx
  src/app/layout.tsx
Labels: 🛠fix

#46 20 feat homepage
  src/Components/Commons/Button/FloatingButton/AddProductModal/index.tsx
  src/Components/Commons/Button/FloatingButton/index.tsx
  src/Components/Commons/Dropdown/DropdownComponent.tsx
  src/Components/Commons/Input/InputContainer.tsx
  src/Components/Commons/ModalContainer/ModalContainer.tsx
  src/Components/HomeComponents/Products/ProductsCategory/index.tsx
  src/Components/HomeComponents/Products/index.tsx
  src/Components/HomeComponents/ReviewRank/index.tsx
  src/Components/HomeComponents/Sidemenu/index.tsx
  src/Components/NavigationBar/Searchbar.tsx
  src/app/SearchContext.tsx
  src/app/layout.tsx
  src/app/page.tsx
Labels: 📃pages

#50 45 feat 비교 상품 교체 모달
  .eslintrc.json
  src/Components/Commons/Icon/CloseButtonIcon.tsx
  src/Components/Commons/ModalContainer/ModalContainer.tsx
  src/Components/Compare/Compare.tsx
  src/Components/Compare/CompareModal.tsx
  src/Context/ModalContext.tsx
  src/app/compare/layout.tsx
  src/app/layout.tsx
Labels: ✨components, feat

#48 39 feat 상품 상세 화면 페이지 만들기
  package-lock.json
  package.json
  public/Icons/gray-logo-icon.svg
  src/Apis/Image/Image.service.ts
  src/Apis/Product/Product.service.ts
  src/Apis/Product/queries.ts
  src/Apis/Product/useProduct.Service.ts
  src/Apis/User/User.service.ts
  src/Apis/requestor.ts
  src/Components/Commons/Button/index.tsx
  src/Components/Commons/ModalContainer/ModalContainer.tsx
  src/Components/ProductDetail/Detail.tsx
  src/Components/ProductDetail/ProductStat.tsx
  src/Components/ProductDetail/Review.tsx
  src/Utils/clip.ts
  src/Utils/isMyProduct.ts
  src/app/Providers.tsx
  src/app/product/[productId]/page.tsx
  src/app/product/layout.tsx
Labels: feat

#53 39 feat 상품 상세 화면 페이지 만들기
  src/Components/HomeComponents/Products/ProductsCategory/index.tsx
  src/Components/Modal/CreateReviewModal.tsx
  src/Components/Modal/EditProductModal.tsx
  src/Components/ProductDetail/Detail.tsx
  src/Components/ProductDetail/FavoriteProductButton.tsx
  src/Components/ProductDetail/ProductDetailContainer.tsx
  src/Components/ProductDetail/ProductStat.tsx
  src/Components/ProductDetail/Review.tsx
  src/Utils/1
Labels: feat

#59 30 feat signpage
  src/Apis/Auth/Auth.service.ts
  src/Apis/Auth/Auth.type.ts
  src/Apis/Auth/queries.ts
  src/Apis/Auth/useAuthService.ts
  src/Apis/Oauth/Oauth.service.ts
  src/Apis/Oauth/Oauth.type.ts
  src/Components/Commons/Input/FileInputForm/FileInputForm.tsx
  src/Components/Commons/Input/InputForm/InputForm.tsx
  src/Components/LoginForm/LoginForm.tsx
  src/Components/SignUpForm/SignUpForm.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/app/globals.css
  src/app/input/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/signup/page.tsx
  src/layouts/AuthLayout.tsx
  tsconfig.json
Labels: 📃pages

#58 20 feat homepage
  src/Apis/requestor.ts
  src/Components/Commons/Button/FloatingButton/AddProductModal/index.tsx
  src/Components/Commons/Button/FloatingButton/index.tsx
  src/Components/Commons/NavigationBar/ClientNavigationBar.tsx
  src/Components/Commons/NavigationBar/ServerNavigationBar.tsx
  src/Components/HomeComponents/Products/ProductsCategory/index.tsx
  src/Components/HomeComponents/ReviewRank/index.tsx
  src/Components/HomeComponents/Sidemenu/index.tsx
  src/app/CategoryContext.tsx
  src/app/layout.tsx
  src/app/page.tsx
Labels: 📃pages

#71 feat 상품 상세 화면 페이지 만들기
  src/Apis/Product/Product.service.ts
  src/Apis/Product/queries.ts
  src/Apis/Product/useProduct.Service.ts
  src/Apis/Review/Review.service.ts
  src/Apis/Review/queries.ts
  src/Components/Commons/Input/FileInputForm/FileInputForm.tsx
  src/Components/ProductDetail/Detail.tsx
  src/Components/ProductDetail/FavoriteProductButton.tsx
  src/Components/ProductDetail/ProductDetailContainer.tsx
  src/Components/ProductDetail/Review.tsx
Labels: feat
